settings:
  docker:
    parent_image: 970547382716.dkr.ecr.us-east-1.amazonaws.com/aczire/llmtwin:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  is_dummy: true # Change this to 'false' to run the evaluation on the full dataset.
