settings:
  docker:
    parent_image: 970547382716.dkr.ecr.us-east-1.amazonaws.com/aczire/llmtwin:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  test_split_size: 0.05
  dataset_type: "preference"
  push_to_huggingface: true
  dataset_id: aczire/llmtwin-dpo
  mock: false
